from flask import Flask, request, jsonify
from flask_cors import CORS
import json
import os

app = Flask(__name__)
CORS(app)

# Mock data for demonstration
MOCK_USERS = {
    'parent': {'password': 'parent123', 'role': 'parent'},
    'student': {'password': 'student123', 'role': 'student'},
    'admin': {'password': 'admin123', 'role': 'admin'}
}

MOCK_STUDY_MODE = {
    'is_enabled': False,
    'start_time': '09:00',
    'end_time': '17:00'
}

MOCK_RULES = [
    {'id': 1, 'rule_type': 'whitelist', 'domain': 'khanacademy.org', 'app_name': 'Khan Academy'},
    {'id': 2, 'rule_type': 'whitelist', 'domain': 'youtube.com', 'app_name': 'YouTube Learning'},
    {'id': 3, 'rule_type': 'blacklist', 'domain': 'tiktok.com', 'app_name': 'TikTok'},
    {'id': 4, 'rule_type': 'blacklist', 'domain': 'instagram.com', 'app_name': 'Instagram'}
]

MOCK_REPORTS = [
    {'date': '2024-01-20', 'study_time_minutes': 120, 'distraction_time_minutes': 60, 'efficiency_percentage': 66.7},
    {'date': '2024-01-19', 'study_time_minutes': 150, 'distraction_time_minutes': 45, 'efficiency_percentage': 76.9},
    {'date': '2024-01-18', 'study_time_minutes': 90, 'distraction_time_minutes': 90, 'efficiency_percentage': 50.0},
    {'date': '2024-01-17', 'study_time_minutes': 180, 'distraction_time_minutes': 30, 'efficiency_percentage': 85.7},
    {'date': '2024-01-16', 'study_time_minutes': 135, 'distraction_time_minutes': 75, 'efficiency_percentage': 64.3},
    {'date': '2024-01-15', 'study_time_minutes': 165, 'distraction_time_minutes': 45, 'efficiency_percentage': 78.6},
    {'date': '2024-01-14', 'study_time_minutes': 105, 'distraction_time_minutes': 105, 'efficiency_percentage': 50.0}
]

MOCK_GAME_SCORES = [
    {'game_type': 'puzzle', 'score': 850, 'level': 5, 'played_at': '2024-01-20 14:30:00'},
    {'game_type': 'snake_ladder', 'score': 720, 'level': 3, 'played_at': '2024-01-19 16:45:00'},
    {'game_type': 'puzzle', 'score': 920, 'level': 6, 'played_at': '2024-01-18 10:15:00'},
    {'game_type': 'snake_ladder', 'score': 680, 'level': 2, 'played_at': '2024-01-17 13:20:00'},
    {'game_type': 'puzzle', 'score': 780, 'level': 4, 'played_at': '2024-01-16 15:30:00'}
]

@app.route('/api/login', methods=['POST'])
def login():
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')
    
    if username in MOCK_USERS and MOCK_USERS[username]['password'] == password:
        return jsonify({
            'success': True,
            'user': {
                'id': 1,
                'username': username,
                'role': MOCK_USERS[username]['role']
            }
        })
    
    return jsonify({'success': False, 'message': 'Invalid credentials'}), 401

@app.route('/api/logout', methods=['POST'])
def logout():
    return jsonify({'success': True})

@app.route('/api/study-mode', methods=['GET', 'POST'])
def study_mode():
    if request.method == 'GET':
        return jsonify(MOCK_STUDY_MODE)
    
    elif request.method == 'POST':
        data = request.get_json()
        MOCK_STUDY_MODE.update(data)
        return jsonify({'success': True})

@app.route('/api/rules', methods=['GET', 'POST', 'DELETE'])
def rules():
    if request.method == 'GET':
        return jsonify(MOCK_RULES)
    
    elif request.method == 'POST':
        data = request.get_json()
        new_rule = {
            'id': len(MOCK_RULES) + 1,
            'rule_type': data['rule_type'],
            'domain': data['domain'],
            'app_name': data.get('app_name')
        }
        MOCK_RULES.append(new_rule)
        return jsonify({'success': True, 'id': new_rule['id']})
    
    elif request.method == 'DELETE':
        rule_id = int(request.args.get('id'))
        MOCK_RULES[:] = [rule for rule in MOCK_RULES if rule['id'] != rule_id]
        return jsonify({'success': True})

@app.route('/api/usage-reports', methods=['GET'])
def usage_reports():
    # Generate simple charts data
    dates = [report['date'] for report in MOCK_REPORTS]
    study_times = [report['study_time_minutes'] for report in MOCK_REPORTS]
    distraction_times = [report['distraction_time_minutes'] for report in MOCK_REPORTS]
    
    total_study = sum(study_times)
    total_distraction = sum(distraction_times)
    
    # Simple chart data (in real app, this would be generated by plotly)
    bar_chart = {
        'data': [
            {'name': 'Study Time', 'x': dates, 'y': study_times, 'type': 'bar', 'marker': {'color': '#0057B7'}},
            {'name': 'Distraction Time', 'x': dates, 'y': distraction_times, 'type': 'bar', 'marker': {'color': '#FF6B6B'}}
        ],
        'layout': {'title': 'Daily Usage Report', 'barmode': 'group'}
    }
    
    pie_chart = {
        'data': [{
            'labels': ['Study Time', 'Distraction Time'],
            'values': [total_study, total_distraction],
            'type': 'pie',
            'marker': {'colors': ['#0057B7', '#FF6B6B']}
        }],
        'layout': {'title': 'Total Usage Distribution'}
    }
    
    # AI recommendation
    if total_distraction == 0:
        ai_recommendation = "Excellent focus! Keep up the great work with your study routine."
    else:
        distraction_ratio = total_distraction / (total_study + total_distraction)
        if distraction_ratio > 0.5:
            ai_recommendation = "Consider enabling stricter study mode. Distraction time is high - try focusing on educational content only."
        elif distraction_ratio > 0.3:
            ai_recommendation = "Good balance! Consider reducing entertainment time slightly to improve study efficiency."
        else:
            ai_recommendation = "Great study efficiency! Your current restrictions are working well."
    
    return jsonify({
        'reports': MOCK_REPORTS,
        'charts': {
            'bar_chart': json.dumps(bar_chart),
            'pie_chart': json.dumps(pie_chart)
        },
        'ai_recommendation': ai_recommendation
    })

@app.route('/api/game-scores', methods=['GET', 'POST'])
def game_scores():
    if request.method == 'GET':
        return jsonify(MOCK_GAME_SCORES)
    
    elif request.method == 'POST':
        data = request.get_json()
        new_score = {
            'game_type': data['game_type'],
            'score': data['score'],
            'level': data.get('level', 1),
            'played_at': '2024-01-20 15:30:00'
        }
        MOCK_GAME_SCORES.insert(0, new_score)
        return jsonify({'success': True})

if __name__ == '__main__':
    print("Starting Telkom Parental Dashboard Backend...")
    print("API available at: http://localhost:5000")
    print("Demo credentials:")
    print("  Parent: username=parent, password=parent123")
    print("  Student: username=student, password=student123")
    print("  Admin: username=admin, password=admin123")
    app.run(host='0.0.0.0', port=5000, debug=True)